### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by gmile** [FrozenCrash/Task#2]
Consider the following use-cases and update implementation plan according:

### Case 1

1. user attempts to update a product.

### Case 2

1. user attempts to create a product.

### Case 3

1. user attempts to remove a product.

### Case 4

1. logged-in user attempts to update a product.

### Case 5

1. logged-in user attempts to create a product.

### Case 6

1. logged-in user attempts to remove a product.

### Case 7

1. admin tries to hide product using product_id `non-existent-id`

### Case 8

1. admin tries to delete product using product_id `non-existent-id`

### Case 9

1. admin tries to update product using product_id `non-existent-id`

### Case 10

1. user tries to obtain product details using product_id `non-existent-id`

### Case 11

1. user tries to obtain product details using product_id `non-existent-id`

### Case 12

1. logged in user tries to add a product to favorites with product_id `non-existent-id`

### Case 13

1. logged in user tries to remove a product from favorites using product_id `non-existent-id`

### Case 14

1. admin deletes product X,
2. admin tries to delete product X again.

### Case 15

1. admin hides product X,
2. admin tries to hide product X again.

### Case 16

1. logged in user adds product X to favorites,
2. logged in user tries to add product X to favorites again.

### Case 17

1. logged in user removes product X from favorites,
2. logged in user tries to removes product X from favorites again.

### Case 18

1. admin creates product X,
2. user obtains ID of product X from a list of all products,
3. admin hides product X,
4. user tries to see details of product X.

### Case 19

1. admin creates product X,
2. user obtains ID of product X from a list of all products,
3. admin hides product X,
4. logged in user tries to add product X to favorites.

### Case 20

1. admin creates product X,
2. user obtains ID of product X from a list of all products,
3. admin deletes product X,
4. logged in user tries to add product X to favorites.

### Case 21

1. admin creates product X,
2. user obtains ID of product X from a list of all products,
3. logged in user adds product X to favorites
4. admin hides product X,
5. logged in user tries to remove product X to favorites.

### Case 22

1. admin creates product X,
2. user obtains ID of product X from a list of all products,
3. logged in user adds product X to favorites
3. admin deletes product X,
4. logged in user tries to remove product X to favorites.

### Case 23 (group of validation cases)

1. admin tries to add/update a product with a price < 0,
2. admin tries to add/update a product no title,
3. admin tries to add/update a product no image URL,
4. admin tries to add/update a product with title from another product,
5. admin tries to add/update a product with incorrect image URL,
5. admin tries to add/update a product with image extension other than "jpeg".

**Comment by FrozenCrash** [comment]
One string in [user-storie.md](https://github.com/FrozenCrash/Task/blob/master/user-stories.md) covered case 2 and case 3

**Comment by gmile** [comment]
Consider the following use-cases and update implementation plan according:

- [x] Case 1
- [x] Case 2
- [x] Case 3
- [x] Case 4
- [x] Case 5
- [x] Case 6
- [x] Case 7
- [x] Case 8
- [x] Case 9
- [x] Case 10
  - [x] remove "load product details", it is not necessary
- [x] Case 11 (duplicate of 10)
- [x] Case 12
  - [x] check if product exists – error case,
  - [x] do not load entire list of products, instead ask DB if product is favorited
- [x] Case 13
  - [x] check if product exists – error case,
  - [x] do not load entire list of products, instead ask DB if product is favorited
- [x] Case 14
- [x] Case 15
- [x] Case 16
  - [x] do not load entire list of favorites
  - [x] ask DB if user has favorited the product
- [x] Case 17
  - [x] similar to 16
  - [x] re-phrase **product list loaded?** question, be more specific
- [x] Case 18
  - [x] similar to 10 - check if product is loaded 
  - [x] handle error
- [x] Case 19
  - [x] similar to 10, 18 - check if product is loaded 
- [x] Case 20
  - [x] similar to 10, 18, 19 - check if product is loaded 
- [x] Case 21
  - [x] similar to 12, 13 - check if **visible** product exists
- [x] Case 22
  - [x] similar to 12, 13 - check if product exists
- [x] Case 23
  - [x] admin tries to add a product with a price < 0,
  - [x] admin tries to add a product no title,
  - [x] admin tries to add a product no image URL,
  - [x] admin tries to add a product with title from another product,
  - [x] admin tries to add a product with incorrect image URL,
  - [x] admin tries to add a product with image extension other than "jpeg".

**Comment by gmile** [comment]
Great job! 🥇

I've added commits cfe0fe5d12aa5fad2faffae140a822ba7889f6d3 and 6e03b2c64c66811ab573a091f9695aa9cbd40689 to address cosmetic things.
